services:
  - type: web
    name: secured-health-records-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/secured-health-records-backend-0.0.1-SNAPSHOT.jar
    plan: starter
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAILERSEND_API_KEY
        sync: false
      - key: MAILERSEND_FROM_EMAIL
        sync: false
      - key: MAILERSEND_FROM_NAME
        value: Secured Health Records
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
